In [1]:
import requests
from datetime import date
import time
import yfinance as yf
from datetime import datetime,timedelta
import os
import json
import csv
import pandas as pd
import numpy as np
# package import statement
import pandas as pd
import arrow
# from market_profile import MarketProfile
signal_data = {}
Master_DF = pd.DataFrame()
prev_date = datetime.now() - timedelta(days=62)
curr_date = datetime.now()
BC = []
TC = []
PP = []

stock = ["UPL","INFY","TATASTEEL","BAJFINANCE","BAJAJ-AUTO","BPCL","HDFC","IOC",
         "HINDALCO","EICHERMOT","SBILIFE","HINDUNILVR","BAJAJFINSV","ITC","BRITANNIA","RELIANCE",
         "DIVISLAB","TCS","WIPRO","ONGC","TECHM","HDFCBANK","HCLTECH","SUNPHARMA","GRASIM","TITAN",
         "INDUSINDBK","CIPLA","HDFCLIFE","JSWSTEEL","NESTLEIND","KOTAKBANK","NTPC","MARUTI","BHARTIARTL","ADANIPORTS",
         "LT","ULTRACEMCO","ASIANPAINT","TATAMOTORS","M&M","SHREECEM","ICICIBANK","AXISBANK","POWERGRID","COALINDIA",
         "HEROMOTOCO","TATACONSUM","SBIN","DRREDDY",]
for ticker in stock:
    signal_data[ticker] = yf.download(ticker+".NS",prev_date,curr_date,interval="1mo")
    my_df_daily = pd.DataFrame(signal_data[ticker])
    my_df_daily.insert(0,'Stock',ticker)
    Master_DF = Master_DF.append(my_df_daily)
    #print(signal_data[ticker])

Master_DF['BC'] = my_df_daily.apply(lambda _: '', axis=1)
Master_DF['PP'] = my_df_daily.apply(lambda _: '', axis=1)
Master_DF['TC'] = my_df_daily.apply(lambda _: '', axis=1)

Master_DF.reset_index(inplace=True)
Master_DF

prev_open = Master_DF['Open']
prev_high = Master_DF['High']
prev_low = Master_DF['Low']
prev_close = Master_DF['Close']

prev_o

Master_DF['PP'] = (prev_high + prev_low + prev_close) / 3
Master_DF['R2'] = Master_DF['PP'] + (prev_high - prev_low)
Master_DF['R1'] = 2*Master_DF['PP'] - prev_low
Master_DF['S1'] = 2*Master_DF['PP'] - prev_high
Master_DF['S2'] = Master_DF['PP'] - (prev_high - prev_low)

Master_DF['BC'] = (prev_high + prev_low)/2

Master_DF['TC'] = (Master_DF['PP'] -Master_DF['BC']) + Master_DF['PP']
Master_DF

for i in Master_DF.index:

    if Master_DF.loc[i,'BC'] > Master_DF.loc[i,'TC']:
        temp = Master_DF.loc[i,'BC']
        Master_DF.loc[i,'BC'] = Master_DF.loc[i,'TC']
        Master_DF.loc[i,'TC'] = temp
#     Master_DF.loc[i,'BC'] = BC_1
#     Master_DF.loc[i,'TC'] = TC_1
#     Master_DF.loc[i,'PP'] = PP

In [2]:
signal_data = {}
Master_DF = pd.DataFrame()
prev_date = datetime.now() - timedelta(days=62)
curr_date = datetime.now()
BC = []
TC = []
PP = []

stock = ["UPL","INFY","TATASTEEL","BAJFINANCE","BAJAJ-AUTO","BPCL","HDFC","IOC",
         "HINDALCO","EICHERMOT","SBILIFE","HINDUNILVR","BAJAJFINSV","ITC","BRITANNIA","RELIANCE",
         "DIVISLAB","TCS","WIPRO","ONGC","TECHM","HDFCBANK","HCLTECH","SUNPHARMA","GRASIM","TITAN",
         "INDUSINDBK","CIPLA","HDFCLIFE","JSWSTEEL","NESTLEIND","KOTAKBANK","NTPC","MARUTI","BHARTIARTL","ADANIPORTS",
         "LT","ULTRACEMCO","ASIANPAINT","TATAMOTORS","M&M","SHREECEM","ICICIBANK","AXISBANK","POWERGRID","COALINDIA",
         "HEROMOTOCO","TATACONSUM","SBIN","DRREDDY",]
for ticker in stock:
    signal_data[ticker] = yf.download(ticker+".NS",prev_date,curr_date,interval="1mo")
    my_df_daily = pd.DataFrame(signal_data[ticker])
    my_df_daily.insert(0,'Stock',ticker)
    Master_DF = Master_DF.append(my_df_daily)
    #print(signal_data[ticker])

Master_DF['BC'] = my_df_daily.apply(lambda _: '', axis=1)
Master_DF['PP'] = my_df_daily.apply(lambda _: '', axis=1)
Master_DF['TC'] = my_df_daily.apply(lambda _: '', axis=1)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [3]:
Master_DF.reset_index(inplace=True)
Master_DF

,Date,Stock,Open,High,Low,Close,Adj Close,Volume,BC,PP,TC
0,2021-08-01,UPL,808.549988,810.650024,714.500000,741.250000,741.250000,56256921.0,,,
1,2021-09-01,UPL,745.150024,772.500000,700.000000,707.700012,707.700012,48032373.0,,,
2,2021-10-01,UPL,707.000000,714.049988,698.250000,712.650024,712.650024,1946653.0,,,
3,2021-08-01,INFY,1627.449951,1757.000000,1619.199951,1706.449951,1706.449951,132748512.0,,,
4,2021-09-01,INFY,1709.500000,1788.000000,1655.000000,1675.199951,1675.199951,113957923.0,,,
...,...,...,...,...,...,...,...,...,...,...,...
161,2021-09-01,SBIN,427.500000,471.899994,425.100006,453.000000,453.000000,408763525.0,,,
162,2021-10-01,SBIN,448.500000,455.549988,443.799988,451.649994,451.649994,14767523.0,,,
163,2021-08-01,DRREDDY,4739.000000,4858.850098,4445.700195,4704.049805,4704.049805,12728213.0,,,
164,2021-09-01,DRREDDY,4739.000000,4996.500000,4687.000000,4880.700195,4880.700195,9530743.0,,,
165,2021-10-01,DRREDDY,4853.000000,4970.000000,4852.250000,4955.850098,4955.850098,341979.0,,,

In [4]:
prev_open = Master_DF['Open']
prev_high = Master_DF['High']
prev_low = Master_DF['Low']
prev_close = Master_DF['Close']

prev_open

0       808.549988
1       745.150024
2       707.000000
3      1627.449951
4      1709.500000
          ...
161     427.500000
162     448.500000
163    4739.000000
164    4739.000000
165    4853.000000
Name: Open, Length: 166, dtype: float64

In [5]:
Master_DF['PP'] = (prev_high + prev_low + prev_close) / 3
Master_DF['R2'] = Master_DF['PP'] + (prev_high - prev_low)
Master_DF['R1'] = 2*Master_DF['PP'] - prev_low
Master_DF['S1'] = 2*Master_DF['PP'] - prev_high
Master_DF['S2'] = Master_DF['PP'] - (prev_high - prev_low)

Master_DF['BC'] = (prev_high + prev_low)/2

Master_DF['TC'] = (Master_DF['PP'] -Master_DF['BC']) + Master_DF['PP']
Master_DF

,Date,Stock,Open,High,Low,Close,Adj Close,Volume,BC,PP,TC,R2,R1,S1,S2
0,2021-08-01,UPL,808.549988,810.650024,714.500000,741.250000,741.250000,56256921.0,762.575012,755.466675,748.358337,851.616699,796.433350,700.283325,659.316650
1,2021-09-01,UPL,745.150024,772.500000,700.000000,707.700012,707.700012,48032373.0,736.250000,726.733337,717.216675,799.233337,753.466675,680.966675,654.233337
2,2021-10-01,UPL,707.000000,714.049988,698.250000,712.650024,712.650024,1946653.0,706.149994,708.316671,710.483348,724.116659,718.383341,702.583354,692.516683
3,2021-08-01,INFY,1627.449951,1757.000000,1619.199951,1706.449951,1706.449951,132748512.0,1688.099976,1694.216634,1700.333293,1832.016683,1769.233317,1631.433268,1556.416585
4,2021-09-01,INFY,1709.500000,1788.000000,1655.000000,1675.199951,1675.199951,113957923.0,1721.500000,1706.066650,1690.633301,1839.066650,1757.133301,1624.133301,1573.066650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,2021-09-01,SBIN,427.500000,471.899994,425.100006,453.000000,453.000000,408763525.0,448.500000,450.000000,451.500000,496.799988,474.899994,428.100006,403.200012
162,2021-10-01,SBIN,448.500000,455.549988,443.799988,451.649994,451.649994,14767523.0,449.674988,450.333323,450.991659,462.083323,456.866659,445.116659,438.583323
163,2021-08-01,DRREDDY,4739.000000,4858.850098,4445.700195,4704.049805,4704.049805,12728213.0,4652.275146,4669.533366,4686.791585,5082.683268,4893.366536,4480.216634,4256.383464
164,2021-09-01,DRREDDY,4739.000000,4996.500000,4687.000000,4880.700195,4880.700195,9530743.0,4841.750000,4854.733398,4867.716797,5164.233398,5022.466797,4712.966797,4545.233398
165,2021-10-01,DRREDDY,4853.000000,4970.000000,4852.250000,4955.850098,4955.850098,341979.0,4911.125000,4926.033366,4940.941732,5043.783366,4999.816732,4882.066732,4808.283366

In [6]:
Master_DF.loc[0,'BC']

762.5750122070312

In [7]:
Master_DF['BC']

0       762.575012
1       736.250000
2       706.149994
3      1688.099976
4      1721.500000
          ...
161     448.500000
162     449.674988
163    4652.275146
164    4841.750000
165    4911.125000
Name: BC, Length: 166, dtype: float64

In [8]:
for i in Master_DF.index:

    if Master_DF.loc[i,'BC'] > Master_DF.loc[i,'TC']:
        temp = Master_DF.loc[i,'BC']
        Master_DF.loc[i,'BC'] = Master_DF.loc[i,'TC']
        Master_DF.loc[i,'TC'] = temp
#     Master_DF.loc[i,'BC'] = BC_1
#     Master_DF.loc[i,'TC'] = TC_1
#     Master_DF.loc[i,'PP'] = PP

In [9]:
Master_DF

,Date,Stock,Open,High,Low,Close,Adj Close,Volume,BC,PP,TC,R2,R1,S1,S2
0,2021-08-01,UPL,808.549988,810.650024,714.500000,741.250000,741.250000,56256921.0,748.358337,755.466675,762.575012,851.616699,796.433350,700.283325,659.316650
1,2021-09-01,UPL,745.150024,772.500000,700.000000,707.700012,707.700012,48032373.0,717.216675,726.733337,736.250000,799.233337,753.466675,680.966675,654.233337
2,2021-10-01,UPL,707.000000,714.049988,698.250000,712.650024,712.650024,1946653.0,706.149994,708.316671,710.483348,724.116659,718.383341,702.583354,692.516683
3,2021-08-01,INFY,1627.449951,1757.000000,1619.199951,1706.449951,1706.449951,132748512.0,1688.099976,1694.216634,1700.333293,1832.016683,1769.233317,1631.433268,1556.416585
4,2021-09-01,INFY,1709.500000,1788.000000,1655.000000,1675.199951,1675.199951,113957923.0,1690.633301,1706.066650,1721.500000,1839.066650,1757.133301,1624.133301,1573.066650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,2021-09-01,SBIN,427.500000,471.899994,425.100006,453.000000,453.000000,408763525.0,448.500000,450.000000,451.500000,496.799988,474.899994,428.100006,403.200012
162,2021-10-01,SBIN,448.500000,455.549988,443.799988,451.649994,451.649994,14767523.0,449.674988,450.333323,450.991659,462.083323,456.866659,445.116659,438.583323
163,2021-08-01,DRREDDY,4739.000000,4858.850098,4445.700195,4704.049805,4704.049805,12728213.0,4652.275146,4669.533366,4686.791585,5082.683268,4893.366536,4480.216634,4256.383464
164,2021-09-01,DRREDDY,4739.000000,4996.500000,4687.000000,4880.700195,4880.700195,9530743.0,4841.750000,4854.733398,4867.716797,5164.233398,5022.466797,4712.966797,4545.233398
165,2021-10-01,DRREDDY,4853.000000,4970.000000,4852.250000,4955.850098,4955.850098,341979.0,4911.125000,4926.033366,4940.941732,5043.783366,4999.816732,4882.066732,4808.283366